module.exports = Object.freeze({
  BUSINESS_INSIGHTS: "businessinsights",
  CONSUMER_INSIGHTS: "consumerinsights",
  DATA_COLLECTION: "Data collection",
  DOCUMENT_VERIFICATION_ERROR: "document/error",
  DOCUMENT_VERIFICATION_REQUEST: "document/request",
  DOCUMENT_VERIFICATION_VERIFY: "document/verify",
  DONE: "Done",
  ERROR: "Error",
  EXPIRED: "Expired",
  INCOME_BANK_VERIFICATION_ERROR: "bank/error",
  INCOME_BANK_VERIFICATION_REQUEST: "bank/request",
  INCOME_BANK_VERIFICATION_VERIFY: "bank/verify",
  INCOME_INSIGHTS: "incomeinsights",
  SECURE_MFA_ERROR: "mfa/error",
  SECURE_MFA_REQUEST: "mfa/request",
  SECURE_MFA_VERIFY: "mfa/verify",
  SEND_EMAIL_COMPLETE: "sendemail/complete",
  SEND_EMAIL_RESTORE: "sendemail/restore",
})
