module.exports = Object.freeze({
  FORM_LOAN_TYPE: "loanTypeForm",
  FORM_YES_OR_NO:"yesOrNoForm",
  FORM_LOAN_DETAILS: "loanDetailsForm",
  FORM_BUSINESS_INFO: "businessInfoForm",
  FORM_BASIC_INFO: "basicInfoForm",
  FORM_DISCLAIMER: "disclaimerForm",
  FORM_SSN: "ssnForm",
  FORM_DLN: "dlnForm",
  FORM_ADDRESS: "addressForm",
  FORM_FORMER_ADDRESS: "formerAddressForm",
  FORM_INCOME_HOUSING: "incomeHousingForm",
  FORM_INCOME_BANK_ACCOUNTS: "incomeAccountsForm",
  FORM_INCOME_INFO: "incomeInfoForm",
  FORM_EMPLOYMENT_INFO: "employmentInfoForm",
  FORM_SUMMARY_INFO: "summaryInfoForm",
  FORM_EXISTING_CUSTOMER_LOADING_DATA :"existingCustomerLoading",
  FORM_EXISTING_CUSTOMER_INFORMATION:"formExistingCustomerInformation",
  FORM_PERSONAL_LOAN:"formPersonalLoan",
  FORM_SMALL_BUSINESS:"formSmallBusiness",
  FORM_EXISTING_CUSTOMER_SUMMARY: "formExistingCustomerSummary",
  FORM_GOVT_DOCUMENT_SCANNING:"formGovtDocumentScanning",
  SUBMIT_APPLICATION_FORM_LOADING:"applicationFormSubmitted"
})
